name: Build Minecraft Paper image based on marctv paper server image

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - main

  
jobs:
  buid:
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: cd minecraft_paper && docker build -t minecraft_paper .

      - name: Push Docker image
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.REGISTRY_TOKEN }}
          docker tag minecraft_paper ghcr.io/kory291/minecraft_paper:latest
          docker push ghcr.io/kory291/minecraft_paper:latest
