name: Build LuaLaTeX image based on ubuntu image

on:
  schedule:
    - cron: 0 0 * * 0

  
jobs:
  buid:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lualatex .

      - name: Push Docker image
