name: Build LuaLaTeX image based on ubuntu image

on:
  schedule:
    - cron: 0 0 * * 0

  
jobs:
  buid:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lualatex .

      - name: Push Docker image
        run: docker login ghcr.io -u ${{ GITHUB_REPOSITORY_OWNER }} -p ${{ secrets.GITHUB_TOKEN }}
        run: docker tag lualatex ghcr.io/${{ GITHUB_REPOSITORY_OWNER }}/lualatex:latest
        run: docker push ghcr.io/${{ GITHUB_REPOSITORY_OWNER }}//lualatex:latest
