name: Build LuaLaTeX image based on ubuntu image

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - main
  workflow_dispatch:

  
jobs:
  buid:
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: cd lualatex && docker build -t lualatex .

      - name: Push Docker image
        run: |
          echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker tag lualatex ghcr.io/kory291/lualatex:latest
          docker push ghcr.io/kory291/lualatex:latest
