name: Build LuaLaTeX image based on ubuntu image

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - main

  
jobs:
  buid:
    runs-on: ubuntu-latest
    conatiner: docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lualatex .

      - name: Push Docker image
        run: |
          docker login ghcr.io -u ${{ env.GITHUB_REPOSITORY_OWNER }} -p ${{ secrets.REGISTRY_TOKEN }}
          docker tag lualatex ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER }}/lualatex:latest
          docker push ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER }}/lualatex:latest
